name: Main workflow

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 15.x]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build | Install
        run: npm ci

      - name: Build | Compile
        run: npm run build

      - name: Build | Test
        run: npm test

      - name: Build | Lint
        run: npm run lint

      - name: Build | Format
        run: npm run format:check
